server:
  port: ${PORT:8080}

spring:
  datasource:
    url: jdbc:sqlite:${user.home}/Documents/tschuba/ez-booth/booth.db
    driverClassName: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
      show_sql: true
  mvc:
    static-path-pattern: /resources/**
  sql:
    init:
      mode: always
  web:
    resources:
      static-locations:
        - file:${tschuba.ez.booth.resourcePath}

tschuba:
  ez:
    booth:
      resourcePath: ${user.home}/Documents/tschuba/ez-booth/static-content
      reporting:
        outputPath: ${tschuba.ez.booth.resourcePath}/reports
        webPath: http://localhost/resources/reports
